class Response
	def self.too_many_char
	  puts "You typed too many characters, please type 4!"
	end 

	def self.not_enough_char
		puts "Not enough characters, please type 4!"
	end

	def self.lose_message(generated_sequence)
		puts "You lose! You're out of guesses! The secret code was #{generated_sequence}, would you like to play again? Select (p)lay or (q)uit"
	end

	def self.color_unknown
		puts "You chose a color thats not in the game. Please choose from r,g,b,y"
	end 

	def self.num_correct_positions_message(number_of_correct_positions)
		puts "You have guessed #{number_of_correct_positions} correct position(s)\nSelect (i)nstructions for help."
	end

	def self.num_correct_colors_message(number_of_correct_colors)
		puts "You have guessed #{number_of_correct_colors} correct color(s)\nSelect (i)nstructions for help"
	end


	def self.win_play_again(guess_count)
		puts "You've won! You had #{guess_count} guess(es) left, would you like to play again? \nSelect (p)lay or (q)uit"
	end

	def self.guess_again(guess_count)
		puts "Guess again! You have #{guess_count} guesses left "
	end

	def self.welcome_message
		puts "******-WELCOME TO MASTERMIND-******"
	end

	def self.instructions__start_message
		puts "A secret code will be generated by the computer consisting of four colors in a specific order. \nYou have fifteen guesses to figure out the secret code. Enter (p)lay or (q)uit."
	end

	def self.game_instructions
		puts "A secret code was generated by the computer consisting of four colors in a specific order.\nTake a guess! (select (c)heat for answer)"
	end

	def self.unknown_input
		puts "Thats not a valid selection."
	end

	def self.goodbye_message
		puts "Thanks for playing!"
	end

	def self.generated_sequence_guess_message
		puts "A SECRET CODE HAS BEEN GENERATED, TAKE A GUESS!"
	end
end

